app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),
    path('add/', views.add_post, name='add_post'),
    path('update/<int:pk>/', views.update_post, name='update_post'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('update_tag/<int:pk>/', views.update_tag, name='update_tag'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField('Tag Name', max_length=30)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('Title', max_length=200)
    text = models.TextField('Content')
    date = models.DateTimeField('Date', default=timezone.now)
    tag = models.ManyToManyField(Tag, verbose_name='Tag', blank=True)

    def __str__(self):
        return self.title

app/forms.py
from django import forms
from .models import Post, Tag


class PostCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        exclude = ('tag',)

# We use inlineformset for tag. When we add new post, tags are listed by inlineformset
TagInlineFormSet = forms.inlineformset_factory(
    Post, Post.tag.through, fields='__all__', can_delete=False
)

# This is easy way of creating a simple form for tag.
TagCreateForm = forms.modelform_factory(Tag, fields='__all__')

# We also use inlineformset for posts. When we add new tag, posts are listed by inlineformset.
PostInlineFormSet = forms.inlineformset_factory(
    Tag, Post.tag.through, fields='__all__', can_delete=False
)

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .forms import PostCreateForm, TagInlineFormSet, TagCreateForm, PostInlineFormSet
from .models import Post

class PostList(generic.ListView):
    model = Post


def add_post(request):
    form = PostCreateForm(request.POST or None)
    context = {'form': form}
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)

        # We need to define which data is related to which, so we set instance=post here.        
        formset = TagInlineFormSet(request.POST, instance=post)
        if formset.is_valid():
            post.save()
            formset.save()
            return redirect('app:index')

        # we store formset with error message in context and it will be passed to template.
        else:
            context['formset'] = formset

    # GET, when we first go to 'add_post' url (add_post view), there is no data in context
    # so we set empty context below. By doing this, contents of formset can be displayed in post_list.html
    else:
        # passing empty formset to template
        context['formset'] = TagInlineFormSet()

    return render(request, 'app/post_form.html', context)



def update_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = PostCreateForm(request.POST or None, instance=post)
    formset = TagInlineFormSet(request.POST or None, instance=post)
    if request.method == 'POST' and form.is_valid() and formset.is_valid():
        form.save()
        formset.save()
        # show update page again here
        return redirect('app:update_post', pk=pk)

    context = {
        'form': form,
        'formset': formset
    }

    return render(request, 'app/post_form.html', context)



def add_tag(request):
    form = TagCreateForm(request.POST or None)
    context = {'form': form}
    if request.method == 'POST' and form.is_valid():
        tag = form.save(commit=False)

        # We need to define which data is related to which, so we set instance=tag here.
        formset = PostInlineFormSet(request.POST, instance=tag)
        if formset.is_valid():
            tag.save()
            formset.save()
            return redirect('app:index')

        # we store formset with error message in context and it will be passed to template.
        else:
            context['formset'] = formset

    # GET, when we first go to 'add_tag' url (add_tag view), there is no data in context
    # so we set empty context below. By doing this, contents of formset can be displayed in tag_form.html
    else:
        # passing empty formset to template
        context['formset'] = PostInlineFormSet()

    return render(request, 'app/tag_form.html', context)


def update_tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    form = TagCreateForm(request.POST or None, instance=tag)
    formset = PostInlineFormSet(request.POST or None, instance=tag)
    if request.method == 'POST' and form.is_valid() and formset.is_valid():
        form.save()
        formset.save()
        # show update page again here
        return redirect('app:update_tag', pk=pk)

    context = {
        'form': form,
        'formset': formset
    }

    return render(request, 'app/tag_form.html', context)

app/templates/app/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Inlineformset_plus_ManyToMany_Field</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/app/post_form.html
{% extends 'app/base.html' %}

{% block content %}
<!-- Because we use file, we need enctype="multipart/form-data" -->
<form action="" method="post" enctype="multipart/form-data">
    <h2>Post</h2>
    {{ form.as_p }}

    <h2>attach file</h2>
    {{ formset.management_form }}
    {% for file_form in formset %}
        {{ file_form.as_p }}
        <hr>
    {% endfor %}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

app/templates/app/post_list.html
{% extends 'app/base.html' %}

{% block content %}
<a href="{% url 'app:add_post' %}" class="btn btn-primary">Add Post</a>
<a href="{% url 'app:add_tag' %}" class="btn btn-primary">Add Tag</a>
<hr>
{% for post in post_list %}
    <p><a href="{% url 'app:update_post' post.pk %}">{{ post.title }}</a></p>
{% endfor %}

{% endblock %}

app/templates/app/tag_form.html
{% extends 'app/base.html' %}

{% block content %}
<!-- Because we use file, we need enctype="multipart/form-data" -->
<form action="" method="post" enctype="multipart/form-data">
    <h2>Post</h2>
    {{ form.as_p }}

    <h2>attach file</h2>
    {{ formset.management_form }}
    {% for file_form in formset %}
        {{ file_form.as_p }}
        <hr>
    {% endfor %}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}